name: truckpro
description: "Truck Safety"
version: 0.1.4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  path_provider:
  photo_view: ^0.14.0
  url_launcher: ^6.1.7
  shared_preferences: ^2.3.0
  marquee: ^2.0.6
  mime: ^2.0.0
  intl: ^0.19.0
  stop_watch_timer: ^3.2.1
  flutter:
    sdk: flutter
  http: ^1.0.0
  jwt_decoder: ^2.0.1
  file_picker: ^8.0.7
  fl_chart: ^0.69.0
  flutter_pdfview: ^1.3.4
  #pdfx: ^2.3.0
  signalr_core: ^1.0.0
  firebase_messaging: ^14.8.2
  flutter_local_notifications: ^17.1.2
  firebase_core: ^2.32.0
  image_picker: ^1.0.7
  image_picker_web: ^3.1.1
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_charts: ^25.1.40
  timeline_tile: ^2.0.0
  
  
dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" 
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/registration_bg.png
    - assets/bgimg.jpeg
    - assets/PDFs/
    - assets/ca/lets-encrypt-r3.pem
