name: truckpro
description: "Truck Safety"
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.13
  marquee: ^2.0.6
  mime: ^2.0.0
  intl: ^0.19.0
  stop_watch_timer: ^3.2.1
  flutter:
    sdk: flutter
  http: ^1.0.0
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" 
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/registration_bg.png
